# Generated by Django 6.0 on 2026-01-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interview_created_at_interviewsession_applied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='transcript',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
