# Generated by Django 6.0 on 2026-01-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_interviewsession_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='answers',
        ),
    ]
